/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt_sanjaya.login;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import pt_sanjaya.home.home;
/**
 *
 * @author Propesiom
 */
public class form_login extends javax.swing.JFrame {
    //deklarasi
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form form_login
     */
    public form_login() {
        initComponents();
        //pemanggilan fungsi koneksi database yang sudah kita buat pada class koneksi.java
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_header = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JTextField();
        jSeparator_username = new javax.swing.JSeparator();
        jPass_field = new javax.swing.JPasswordField();
        jSeparator_password = new javax.swing.JSeparator();
        pnl_sumbit = new javax.swing.JPanel();
        lbl_sumbit = new javax.swing.JLabel();
        ckbox_showpass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_header.setBackground(new java.awt.Color(51, 51, 240));

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt_sanjaya/login/icon/icons8-delete-filled-20.png"))); // NOI18N
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_headerLayout.createSequentialGroup()
                .addGap(0, 546, Short.MAX_VALUE)
                .addComponent(lbl_close))
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_close))
        );

        getContentPane().add(panel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 566, 20));

        panel_login.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SIGN IN");

        lbl_username.setBackground(panel_login.getBackground());
        lbl_username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lbl_username.setText("Username");
        lbl_username.setBorder(null);
        lbl_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usernameMouseClicked(evt);
            }
        });
        lbl_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_usernameActionPerformed(evt);
            }
        });

        jSeparator_username.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator_username.setForeground(new java.awt.Color(0, 0, 0));

        jPass_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPass_field.setText("Password");
        jPass_field.setBorder(null);
        jPass_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPass_fieldMouseClicked(evt);
            }
        });
        jPass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPass_fieldActionPerformed(evt);
            }
        });

        jSeparator_password.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator_password.setForeground(new java.awt.Color(0, 0, 0));

        pnl_sumbit.setBackground(new java.awt.Color(51, 51, 240));
        pnl_sumbit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnl_sumbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_sumbitMouseClicked(evt);
            }
        });

        lbl_sumbit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_sumbit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sumbit.setText("LOGIN");

        javax.swing.GroupLayout pnl_sumbitLayout = new javax.swing.GroupLayout(pnl_sumbit);
        pnl_sumbit.setLayout(pnl_sumbitLayout);
        pnl_sumbitLayout.setHorizontalGroup(
            pnl_sumbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sumbitLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lbl_sumbit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_sumbitLayout.setVerticalGroup(
            pnl_sumbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sumbitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_sumbit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ckbox_showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbox_showpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_username)
                            .addComponent(jSeparator_username)
                            .addComponent(jSeparator_password, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnl_sumbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addComponent(jPass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckbox_showpass)))))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator_username, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbox_showpass))
                .addGap(1, 1, 1)
                .addComponent(jSeparator_password, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_sumbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(panel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 570, 350));

        setSize(new java.awt.Dimension(566, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
   
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_usernameActionPerformed

    private void pnl_sumbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sumbitMouseClicked
        // TODO add your handling code here:
        home hm = new home();
        try {
            sql = "SELECT * FROM login WHERE username = '"+lbl_username.getText()+"'AND password ='"+jPass_field.getText()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
                if(lbl_username.getText().equals(rs.getString("username")) && jPass_field.getText().equals(rs.getString("password"))){
                     JOptionPane.showMessageDialog(null, "berhasil login"); 
                     
                     hm.setVisible(true);
                     this.setVisible(false);
                }
            }else{
                 JOptionPane.showMessageDialog(null, "username atau password salah");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_pnl_sumbitMouseClicked

    private void lbl_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usernameMouseClicked
        // TODO add your handling code here:
        lbl_username.setText("");
    }//GEN-LAST:event_lbl_usernameMouseClicked

    private void jPass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPass_fieldActionPerformed

    private void jPass_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPass_fieldMouseClicked
         jPass_field.setText("");
    }//GEN-LAST:event_jPass_fieldMouseClicked

    private void ckbox_showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbox_showpassActionPerformed
        //logic show pass
        if(ckbox_showpass.isSelected()){
            jPass_field.setEchoChar((char)0);
        }else{
            jPass_field.setEchoChar('*');
        }
    }//GEN-LAST:event_ckbox_showpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbox_showpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPass_field;
    private javax.swing.JSeparator jSeparator_password;
    private javax.swing.JSeparator jSeparator_username;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_sumbit;
    private javax.swing.JTextField lbl_username;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel pnl_sumbit;
    // End of variables declaration//GEN-END:variables
}
